# Generated by Django 3.2.7 on 2021-09-29 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('permission', models.CharField(choices=[('N', 'None'), ('Sup', 'Support'), ('Sal', 'Sales'), ('Adm', 'Admin')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
